Document: qmpdclient
Title: Debian qmpdclient Manual
Author: <insert document author here>
Abstract: This manual describes what qmpdclient is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qmpdclient/qmpdclient.sgml.gz

Format: postscript
Files: /usr/share/doc/qmpdclient/qmpdclient.ps.gz

Format: text
Files: /usr/share/doc/qmpdclient/qmpdclient.text.gz

Format: HTML
Index: /usr/share/doc/qmpdclient/html/index.html
Files: /usr/share/doc/qmpdclient/html/*.html
